export const ApartmentStatus = {
  AVAILABLE: "available",
  RENTED: "rented",
  SOLD: "sold",
  UNAVAILABLE: "unavailable",
};

export const ApartmentDirection = {
  NORTH: 1,
  NORTHEAST: 2,
  EAST: 3,
  SOUTHEAST: 4,
  SOUTH: 5,
  SOUTHWEST: 6,
  WEST: 7,
  NORTHWEST: 8,
};

export const ApartmentRentSchema = {
  DAILY: "daily",
  WEEKLY: "weekly",
  MONTHLY: "monthly",
};

export class ApartmentUnit {
  constructor(
    unitCode,
    floor,
    rooms,
    direction,
    status,
    balcony,
    furnished,
    rentPrice,
    rentSchema,
    sellPrice,
    residentId
  ) {
    this.id = ""; // (autogenerated at backend)
    this.unitCode = unitCode || "";
    this.floor = floor || null;
    this.rooms = rooms || "";
    this.direction = direction || ""; // (value from ApartmentDirection)
    this.status = status || ""; // (value from ApartmentStatus)
    this.balcony = balcony || "";
    this.furnished = furnished || "";
    this.rentPrice = rentPrice || 0;
    this.rentSchema = rentSchema || ""; // (value from ApartmentRentSchema)
    this.sellPrice = sellPrice || 0;
    this.residentId = residentId || ""
  }
}

export class Transaction {
  constructor(
    id,
    unitId,
    residentId,
    transactionDate,
    rentEndDate,
    rentStartDate,
    billingDate,
    period,
    price,
    profit,
    schema
  ) {
    this.id = ""; // (autogenerated at backend)
    this.unitId = unitId || ""; // (id from ApartmentUnit)
    this.residentId = residentId || ""; // (id from Resident)
    this.transactionDate = transactionDate || "";
    this.rentStartDate = rentStartDate || "";
    this.rentEndDate = rentEndDate || "";
    this.billingDate = billingDate || "";
    this.period = period || "";
    this.price = price || "";
    this.profit = profit || "";
    this.schema = schema || "";
  }
}

export const MaritalStatus = {
  SINGLE: 'single',
  TAKEN: 'taken',
  MARRIED: 'married',
  DIVORCED: 'divorced',
  JONES: 'jones',
};

export class Resident {
  constructor(
    id,
    fullName,
    email,
    phone,
    maritalStatus,
    dependents,
    birthDate
  ) {
    this.id = ''; // (autogenerated at backend)
    this.fullName = fullName;
    this.email = email;
    this.phone = phone;
    this.maritalStatus = maritalStatus; // (value from MaritalStatus)
    this.dependents = dependents;
    this.birthDate = birthDate;
  }
}
