export const MaritalStatus = {
  SINGLE: 'single',
  TAKEN: 'taken',
  MARRIED: 'married',
  DIVORCED: 'divorced',
  JONES: 'jones',
};

export class Resident {
  constructor(
    id,
    fullname,
    email,
    phone,
    maritalStatus,
    dependents,
    birthDate
  ) {
    this.id = ''; // (autogenerated at backend)
    this.fullname = fullname;
    this.email = email;
    this.phone = phone;
    this.maritalStatus = maritalStatus; // (value from MaritalStatus)
    this.dependents = dependents;
    this.birthDate = birthDate;
  }
}
