export class Transaction {
  constructor(
    id,
    unitId,
    residentId,
    transactionDate,
    rentEndDate,
    rentStartDate,
    billingDate,
    period,
    price,
    profit
  ) {
    this.id = ""; // (autogenerated at backend)
    this.unitId = unitId || ""; // (id from ApartmentUnit)
    this.residentId = residentId || ""; // (id from Resident)
    this.transactionDate = transactionDate || "";
    this.rentStartDate = rentStartDate || "";
    this.rentEndDate = rentEndDate || "";
    this.billingDate = billingDate || "";
    this.period = period || "";
    this.price = price || "";
    this.profit = profit || "";
  }
}
